### ISSUE TITLE
One doesn't know why the error was caused

### ISSUE THREAD

**Issue by CNDogc** [WekyJay/WkKit_WiKi#1]
[13:00:25 ERROR]: Could not pass event PlayerJoinEvent to WkKit v1.2.4 
java.lang.NullPointerException: Cannot invoke "org.bukkit.configuration.file.YamlConfiguration.getString(String)" because "this.yaml" is null 
 at cn.wekyjay.www.wkkit.tool.ChackPluginVersion.getLatestVersion(ChackPluginVersion.java:63) ~[WkKit-1.2.4.jar:?] 
 at cn.wekyjay.www.wkkit.tool.ChackPluginVersion.onOpLogin(ChackPluginVersion.java:129) ~[WkKit-1.2.4.jar:?] 
 at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor559.execute(Unknown Source) ~[?:?] 
 at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?] 
 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:git-Purpur-2095] 
 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?] 
 at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.2.jar:git-Purpur-2095] 
 at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.2.jar:git-Purpur-2095] 
 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?] 
 at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:346) ~[purpur-1.20.2.jar:git-Purpur-2095] 
 at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:130) ~[purpur-1.20.2.jar:git-Purpur-2095] 
 at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:18) ~[purpur-1.20.2.jar:git-Purpur-2095] 
 at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.a(ServerboundFinishConfigurationPacket.java:9) ~[purpur-1.20.2.jar:git-Purpur-2095] 
 at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:53) ~[?:?] 
 at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.2.jar:git-Purpur-2095] 
 at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?] 
 at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?] 
 at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1351) ~[purpur-1.20.2.jar:git-Purpur-2095] 
 at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193) ~[purpur-1.20.2.jar:git-Purpur-2095] 
 at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?] 
 at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1328) ~[purpur-1.20.2.jar:git-Purpur-2095] 
 at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1321) ~[purpur-1.20.2.jar:git-Purpur-2095] 
 at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?] 
 at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1398) ~[purpur-1.20.2.jar:git-Purpur-2095] 
 at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[purpur-1.20.2.jar:git-Purpur-2095] 
 at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.20.2.jar:git-Purpur-2095] 
 at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by WekyJay** [comment]
This is the reason why my version update server is down, please update to 1.2.5, the issue has been fixed.Thank you for your suppose！
